### ISSUE TITLE
[NIP-01] Have the relays handle JSON5 requests

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#26]
Since the requests are so human friendly (a bit like IRC is), maybe relays could support alternative flavours of JSON like [JSON5](https://json5.org/)?

**Comment by fiatjaf** [comment]
That's cool, but my approach to this is that any new thing we force everybody to support becomes a hurdle for implementors and reduces the chances of the protocol to be successful.

Having two ways of doing the same thing goes very against what I think is right for a protocol. It's exponentially better to have a single way, even if that way is very bad.

**Comment by lenormf** [comment]
Since JSON5 is a subset of JSON, valid JSON is valid JSON5. That means that supporting JSON5 on the relay’s side could be made optional, and that would allow users to write more human readable events.

**Comment by fiatjaf** [comment]
I don't think it's possible to write events by hand since they require cryptographic hashes and signatures. Also at least in my mind no one should be writing these events by hand at all. Each event must have a different kind of content based on its kind, and besides "text_note" events they will all be weird and unreadable already, I imagine.

I sympathize with your desire to have human-readable stuff (for example, I like how HTTP is human-readable and HTTPS/HTTP2 are not), but I think just normal JSON is already fairly readable, specially if you format it in a pretty way. And there could be client-side tools that allow you to convert JSON5 or YAML or other stuff into standard JSON events, if you have a use case for that.

Also, from the standardization side, asking implementors to support JSON5, even if only JSON5, is worse than asking them to support JSON, because JSON is already built-in in all languages and standard libraries, JSON5 is not.

**Comment by lenormf** [comment]
Fair.
