### ISSUE TITLE
[NIP-01] Disowning an event already sent to a relay

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#29]
If a user makes a mistake (or a client bug occurs) that results in an event being sent to a relay, how could they remove it?

If deleting an arbitrary event isn’t desirable, maybe relays should have a grace period that allows clients to correct a mistake shortly after the event was sent?

**Comment by fiatjaf** [comment]
I was thinking about the terrible idea of posting "tombstone" events that other protocols do and saying to myself that is so bad it's better to not have anything. Also it wouldn't fit Nostr since the id is a checksum.

But given the architecture choices of Nostr I think we should probably have a `DELETE` message, that makes sense.

Hmm, no, that doesn't make sense because it would have to be signed.

So I guess we can have a tombstone event that references the previous event and relays can just delete the referenced event when they get a tombstone, they don't have to keep either.

**Comment by scsibug** [comment]
I like the idea of an event kind that would indicate the user wants to disown/delete a referenced event id.  The simplest option would be placing the event id in the content field.

An alternative, which I think I prefer, is to use the event tag to refer to one or many events for deletion.  Then, the content can serve as a "reason" for deletion, which I think is quite useful.  Essentially, event cancellation with a user-specified message.  This is also more space-efficient for mass-deletion, one event could cancel multiple others.
