### ISSUE TITLE
[NIP-01] `NOTICE`s may be redundant with encrypted direct messages (NIP-04)

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#30]
Notices could be direct messages sent by the relay’s identity.

**Comment by fiatjaf** [comment]
Indeed they could.

But on the other hand that would assume all clients have NIP-04 interfaces implemented.

And also one might not know a relay's identity. We don't want to force relays to have identities and be forced to keep keys safe etc.

And I think it fits better -- since one already has a connection to a relay that is self-contained and contextual -- to have these notices be just easy to send these (which are basically error messages) directly from the relay's request handling flow and handled in special way by the client.

Also imagine relay error notices "couldn't fetching anything you wanted" being propagated through other relays as NIP-04 events. Sounds like a preventable nightmare.
