### ISSUE TITLE
[NIP-01] Hint at the format of an event’s content

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#33]
Should events have a field that hints at the format of their contents? It could be a MIME type or one of the only formats (Markdown?) accepted by the protocol.

Or should relay try to guess the format using heuristic, the same way the `file` utility does?

**Comment by fiatjaf** [comment]
Event contents should be specified in the NIP according to their kind. That's the point of having different kinds.

If an application is using a nonstandard event kind then it will still know the event format because it would be something they invented. And then that can be standardized later so other applications can learn the format.

**Comment by lenormf** [comment]
The NIP indicates that `content` is text, and nothing else. A user posting an essay/article might want to publish it in Markdown (for example), but the relay might display it unformatted.

Having a field that hints at the format of `content` would allow relays to notify clients how to render text on their UI, instead of plain text by default.
