### ISSUE TITLE
[NIP-01] Subscription for Author/Authors redundant

### ISSUE THREAD

**Issue by scsibug** [fiatjaf/nostr#34]
The "author" and "authors" fields in a REQ message are redundant.

Since these fields are ANDed together, if a subscription filter includes author=A, and authors=[B,C], then it will never return any results.  If the filter uses author=A, authors=[A,B,C], it is equivalent to only sending the authors field.

Since it never makes sense to use both of these fields at the same time, and "authors" is more general than "author", I suggest dropping the "author" field from REQ altogether.

**Comment by fiatjaf** [comment]
@kukks do you remember the reason for this? I also have a vague memory of there being a reason, but was checking in my own implementation and used all my reasoning power but couldn't find it. It seems to make absolute sense to drop it. That will make the protocol simpler at no cost.

**Comment by fiatjaf** [comment]
OK, I remember now.

The `authors` field is used to request events from multiple different authors. For example, if you're doing a Twitter clone and want posts from a list of pubkeys you follow you'll use the `authors` combined with a `kind: 1`, for example.

Meanwhile, if you want posts from a single pubkey you would use `author`.

It showed up this way because first I had only the `author` field and later added `authors`.

It was good to remember the reason on why this exists, but of course it makes no sense to keep both fields, we can have just `authors` and set it to an array containing a single element and it will be the same.

**Comment by fiatjaf** [comment]
I'll go ahead and remove the `author` field from the spec, it will be better without it.
