### ISSUE TITLE
What happens when something illegal is posted?

### ISSUE THREAD

**Issue by TestAccountYC** [fiatjaf/nostr#44]
While the goal of creating a truly censorship-resistant social network seems to be very appealing I am curious about the issue of what happens when posts with content related to selling harmful drugs, human trafficking, and child pornography is posted.
This type of content doesn't just need to be censored but also needs to be reported to authorities with the true identity of the people involved. 

Here are a few questions about this:
- Does the platform have no accountability in such situations?
- Even if the poster of such content gets banned from many relays there is still some chance of that post being visible to many other innocent (and in case of kids/teenagers, impressionable) people. How does the platform make sure that this doesn't happen?
- How can authorities take action against the parties involved in running these accounts? If that is not possible then are we just making a platform that enables illegal activities in the name of privacy and freedom, and disregarding the moral and ethical responsibilities as human?

(Sorry if this is discussed somewhere, please point me towards that discussion/document if applicable) 
P.S. These questions are not meant to belittle the efforts of the people involved but come from a genuine place of concern

**Comment by scsibug** [comment]
I'm sure others have their own opinions on this, but i'll give my own thoughts as someone currently running a relay.

There are discussions that will need to happen regarding how relay operators and users deal with unwanted content - whether spam, or data that is illegal to possess, or hiding illegal transactions.  There are many options here, and not one that will be appropriate for everyone.

Platforms have various amounts of legal accountability according to the jurisdiction they operate in, so clearly that does exist.  Other decentralized platforms with far more privacy features than Nostr have shown that authorities already have the tools to enforce their laws.

The protocol itself has no opinions on what is "objectionable" to any given person or authority.  Individuals make their own decisions about what addresses to follow.  Relays can also have their own policies, and govern themselves.  The protocol does nothing to preclude adding out-of-band authentication in order to allow publishing to a relay, and we may very well see more of that when spam becomes a bigger problem.

I'm unsure how Nostr is any different with respect to this problem than Bitcoin, HTTP, Usenet, bittorrent or email.  In fact, since events can easily be scrubbed, it is much _better_ than bitcoin, which already has illegal content stored within it which cannot be removed.

The first solution that comes to mind, is ensuring that there is a mechanism for advertising contact information for relay operators (although... we already do so via DNS).  That would make it possible for users to easily (or automatically) generate reports of content that the relay operator should consider for removal.  I certainly would be open to having a dedicated address I could check for reported issues, and maintain a server-side list of banned addresses or event IDs.

Nostr isn't about preventing that kind of small-scale censorship within a community; rather, it prevents me from making that decision on behalf of all users of the protocol across the world (such as Twitter, Facebook, etc. can and do).  It is "censorship-resistant", not "censorship-proof".

Thanks for the comment and interest.

**Comment by fiatjaf** [comment]
The problem with these concerns is that they are not compatible with the goal of censorship-resistance. Anything that can be used against child pornographers will be used against political dissidents, therefore anytime you defend one you're defending the other, and vice-versa.

Child pornographers already can spread their pornography online today through many means -- and I can only imagine they are fine with the current state of affairs because very few people want to see these things and the ones that do probably know where to look.

On the other hand, political dissidents may have millions of interested readers so they need an open platform like Nostr to be able to be reachable, and they don't have any today -- as any political dissident is easily bannable from Twitter, YouTube, Facebook and so on, and then they can only communicate with a few readers that care enough to follow them into the dark corners of the internet to where they move.

Therefore I think defending the innocent people that are being censored by the State is better than trying to prevent misuse of the internet.
