### ISSUE TITLE
Functional difference from email?

### ISSUE THREAD

**Issue by lf94** [fiatjaf/nostr#6]
Genuine question!

Isn't this essentially just stripped-down email?

**Comment by fiatjaf** [comment]
Well, I guess we can list many differences and similarities.

One big and crucial difference in my opinion is the name system. The fact that each user is identified by a public key and thus no message from them can be forged and no provider can deprive them of their identity.

A smaller but also notable difference is that clients use a "pull" model rather than "push".

Now that I'm thinking about it Mastodon and friends are much more similar to email actually, and both share many of their problems (which would be in both cases mostly fixed if everybody ran their own server, which in both cases is very impractical).

**Comment by lf94** [comment]
Thank you for the response :)

The design around "cryptographic keys first" is probably my favorite part of nostr.

The relay model is also great.

I'll close the issue now that it's been answered!
