### ISSUE TITLE
Http support?

### ISSUE THREAD

**Issue by cristiano-belloni** [fiatjaf/nostr#9]
It'd be great to have http support too (implemented via polling) along with web sockets in the protocol. It'd be interesting to write a serverless plug and play relay based on lambdas / functions.

**Comment by fiatjaf** [comment]
There could be that, and I realize that HTTP is simpler to work with and use in these platforms, I just thought polling was too wasteful and stateless, so how would the relay know what keys are being followed by each longpoll request? Not sure if that complicates everything, or maybe it is better, I don't know at this point.

I also think there should be a single way the clients and relays can communicate otherwise the incompatibility will kill us all. So that leaves the question: should trash the Websocket approach and do everything with HTTP?

The first version of the protocol used a combination of HTTP and SSE, then I changed it to just one stateful Websocket for each client-relay, but now I'm thinking just simple old HTTP would be better indeed. Ultimately I don't know if any of this matters.

**Comment by cristiano-belloni** [comment]
> There could be that, and I realize that HTTP is simpler to work with and use in these platforms, I just thought polling was too wasteful and stateless, so how would the relay know what keys are being followed by each longpoll request? Not sure if that complicates everything, or maybe it is better, I don't know at this point.

Servers can store sessions in a database. Redis comes to mind but it's not too wasteful doing that with something like Firebase, provided that the polling interval is not incredibly short.

Alternatively, keys can be exchanged with each request. If they're too many, maybe a small bitmap containing a [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) can be sent and the client can reject the false positives.

> Ultimately I don't know if any of this matters

It can be an extension of the protocol even if it doesn't get implemented by your reference implementation; if the project is successful, other people will do that. I just think it would be even more resistant (and appealing) to allow people to spawn ready-made free-tier relays on Firebase or even repl.it, without having to configure (and pay for) a machine somewhere.
